### ISSUE TITLE
Need instructions for creating Couchbase to be accessed from Lambda

### ISSUE THREAD

**Issue by dwschulze** [arun-gupta/serverless#8]
The HelloCouchbase example on your blog does not mention how to set up a Couchbase instance for use by the lambda.

**Comment by arun-gupta** [comment]
You can refer to https://github.com/couchbase-guides/couchbase-amazon-cli for setting up a Couchbase instance on EC2 as explained at https://github.com/couchbase-guides/couchbase-amazon-cli.
